### ISSUE TITLE
MVP 2 Posts

### ISSUE THREAD

**Issue by ThinkSalat** [ThinkSalat/Trendr#3]
- [x] set up aws bucket
- [x] set up active storage for post upload and retrieval
- [x] set up model, api endpoint, controller for posts
- [x] set up model, api endpoint, controller for postsMedias
- [x] allow user to upload single photo
- [x] allow user to upload multiple photos as a photoset
- [x] allow user to upload gif
- [x] style post container to allow photosets
- [x] style navbar for new posts
- [x] seed data from tumblr's api
- [x] style post container
- [x] style post container buttons at bottom (won't do anything until implemented--grey out until then)
- [x] style new post form

**Comment by andywynkoop** [comment]
- [x] Update live link in the wiki to link to the deployed version
- [x] Remember to remove redux logger and all console logs from the app before deploying
When logged in with a new account:
- [x] When trying to post text only, I get a 422 error
- [x] When posting a photo, I also get 422 error
- [ ] I am unable to see any posts
- [ ] From the demo user, it looks like the post is successful, but there is no information (other than the logger) to indicate I uploaded successfully

**Comment by ThinkSalat** [comment]
The posts and ability to see the uploaded post will be handled in next mvp, which is the main feed. Tumblr actually doesn't have any confirmation, it just redirects to the feed, and usually your last post is on top.

**Comment by andywynkoop** [comment]
Okay in that case I'll just make sure everything works through posting
